/*
 * generated by Xtext 2.30.0
 */
package wodel.dsls.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ASPLEProposalProvider extends AbstractASPLEProposalProvider {
}
