<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mutatext" nsURI="http://mutatext/1.0" nsPrefix="mutatext">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valid" lowerBound="1" eType="#//Text"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invalid" lowerBound="1"
        eType="#//Text" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text">
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" upperBound="-1"
        eType="#//Word" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Word" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Word">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VariableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="object"/>
    <eLiterals name="attName" value="1"/>
    <eLiterals name="oldValue" value="2"/>
    <eLiterals name="newValue" value="3"/>
    <eLiterals name="refName" value="4"/>
    <eLiterals name="fromObject" value="5"/>
    <eLiterals name="oldFromObject" value="6"/>
    <eLiterals name="srcRefName" value="7"/>
    <eLiterals name="toObject" value="8"/>
    <eLiterals name="oldToObject" value="9"/>
    <eLiterals name="firstObject" value="10"/>
    <eLiterals name="firstRefName" value="11"/>
    <eLiterals name="firstFromObject" value="12"/>
    <eLiterals name="firstToObject" value="13"/>
    <eLiterals name="secondObject" value="14"/>
    <eLiterals name="secondRefName" value="15" literal="secondRefName"/>
    <eLiterals name="secondFromObject" value="16"/>
    <eLiterals name="secondToObject" value="17"/>
    <eLiterals name="firstAttName" value="18"/>
    <eLiterals name="firstValue" value="19"/>
    <eLiterals name="secondAttName" value="20"/>
    <eLiterals name="secondValue" value="21"/>
    <eLiterals name="value" value="22"/>
    <eLiterals name="describedObject" value="23" literal="describedObject"/>
    <eLiterals name="describedFromObject" value="24" literal="describedFromObject"/>
    <eLiterals name="describedOldFromObject" value="25" literal="describedOldFromObject"/>
    <eLiterals name="describedToObject" value="26" literal="describedToObject"/>
    <eLiterals name="describedOldToObject" value="27" literal="describedOldToObject"/>
    <eLiterals name="describedFirstObject" value="28" literal="describedFirstObject"/>
    <eLiterals name="describedFirstFromObject" value="29" literal="describedFirstFromObject"/>
    <eLiterals name="describedFirstToObject" value="30" literal="describedFirstToObject"/>
    <eLiterals name="describedSecondObject" value="31" literal="describedSecondObject"/>
    <eLiterals name="describedSecondFromObject" value="32" literal="describedSecondFromObject"/>
    <eLiterals name="describedSecondToObject" value="33" literal="describedSecondToObject"/>
  </eClassifiers>
</ecore:EPackage>
