/*
 * generated by Xtext 2.30.0
 */
package wodel.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ASPLEUiModule extends AbstractASPLEUiModule {

	public ASPLEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
