/*
 * generated by Xtext 2.40.0
 */
package wodel.dsls.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import wodel.dsls.asple.ui.internal.AspleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ASPLEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AspleActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AspleActivator activator = AspleActivator.getInstance();
		return activator != null ? activator.getInjector(AspleActivator.WODEL_DSLS_ASPLE) : null;
	}

}
