/*
 * generated by Xtext 2.41.0
 */
package wodeledu.dsls.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelDrawAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("wodeledu/dsls/parser/antlr/internal/InternalModelDraw.tokens");
	}
}
