package wodeledu.dsls.generator;

import com.google.common.collect.Iterables;
import java.util.ArrayList;
import java.util.List;
import modeldraw.MutatorDraw;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import wodel.utils.manager.JavaUtils;
import wodel.utils.manager.ModelManager;
import wodel.utils.manager.ProjectUtils;

@SuppressWarnings("all")
public class ModelDrawPyCodeGenerator extends AbstractGenerator {
  private String fileName;

  private String className;

  private List<EPackage> metamodel;

  private List<EClass> roots;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      int i = 0;
      this.fileName = resource.getURI().lastSegment();
      String _replaceAll = this.fileName.replaceAll(".draw", "").replaceAll("[.]", "_");
      String _plus = (_replaceAll + ".draw");
      this.fileName = _plus;
      Iterable<MutatorDraw> _filter = Iterables.<MutatorDraw>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), MutatorDraw.class);
      for (final MutatorDraw e : _filter) {
        {
          if ((i == 0)) {
            String _replace = this.fileName.replace(".draw", "");
            String _plus_1 = (_replace + "Draw.java");
            this.fileName = _plus_1;
          } else {
            String _replace_1 = this.fileName.replace(".draw", "");
            String _plus_2 = (_replace_1 + Integer.valueOf(i));
            String _plus_3 = (_plus_2 + "Draw.java");
            this.fileName = _plus_3;
          }
          ArrayList<EPackage> _arrayList = new ArrayList<EPackage>();
          this.metamodel = _arrayList;
          this.metamodel.addAll(ModelManager.loadMetaModel(e.getMetamodel()));
          ArrayList<EClass> _arrayList_1 = new ArrayList<EClass>();
          this.roots = _arrayList_1;
          this.roots.addAll(ModelManager.getRootEClasses(this.metamodel));
          this.className = this.fileName.replaceAll("Draw.java", "");
          fsa.generateFile(((("mutator/" + this.className) + "/") + this.fileName), JavaUtils.format(this.compile(e), false));
          i++;
        }
      }
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  public static IProject projectOf(final Resource r) {
    Object _xblockexpression = null;
    {
      URI _uRI = null;
      if (r!=null) {
        _uRI=r.getURI();
      }
      final URI uri = _uRI;
      if (((uri != null) && uri.isPlatformResource())) {
        final String projectName = uri.segment(1);
        return ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
      }
      _xblockexpression = null;
    }
    return ((IProject)_xblockexpression);
  }

  public CharSequence compile(final MutatorDraw draw) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("//");
    IProject project = ModelDrawPyCodeGenerator.projectOf(draw.eResource());
    _builder.newLineIfNotEmpty();
    String _xblockexpression = null;
    {
      IProject _xifexpression = null;
      if ((project != null)) {
        _xifexpression = project;
      } else {
        _xifexpression = ProjectUtils.getProject();
      }
      project = _xifexpression;
      _xblockexpression = "";
    }
    _builder.append(_xblockexpression);
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("//");
    String _replace = project.getLocation().toFile().getPath().replace("\\", "/");
    String folder = (_replace + "/");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("package mutator.");
    _builder.append(this.className);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.BufferedReader;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.File;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.FileNotFoundException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.FileReader;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.PrintWriter;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.IOException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.io.UnsupportedEncodingException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.lang.InterruptedException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.Arrays;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.HashMap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.Map;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.LinkedHashMap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EAttribute;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EClass;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EEnum;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EEnumLiteral;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EObject;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EPackage;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EReference;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.EStructuralFeature;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.resource.Resource;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.emf.ecore.util.EcoreUtil;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.exceptions.MetaModelNotFoundException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.exceptions.ModelNotFoundException;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.manager.ProjectUtils;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.manager.ModelManager;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.manager.Py2Code;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import wodel.utils.manager.DrawUtils.LabelStyle;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.core.runtime.IProgressMonitor;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.lang.reflect.InvocationTargetException;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.core.commands.AbstractHandler;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.core.commands.ExecutionEvent;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.core.commands.ExecutionException;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.core.resources.IProject;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.jface.dialogs.ProgressMonitorDialog;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.jface.operation.IRunnableWithProgress;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.swt.widgets.Display;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.eclipse.swt.widgets.Shell;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.jsoup.Jsoup;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import org.jsoup.nodes.Document;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public class ");
    _builder.append(this.className, "\t");
    _builder.append("Draw extends AbstractHandler implements wodeledu.extension.run.commands.IMutatorDraw {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("private class RunMutatorPyCodeWithProgress implements IRunnableWithProgress {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("public void run(IProgressMonitor monitor) throws InvocationTargetException, InterruptedException {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("generate(monitor);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("catch (MetaModelNotFoundException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("catch (ModelNotFoundException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("catch (FileNotFoundException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void generate(IProgressMonitor monitor) throws MetaModelNotFoundException, ModelNotFoundException, FileNotFoundException {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String metamodel = \"");
    String _replace_1 = ModelManager.getMetaModel().replace("\\", "/");
    _builder.append(_replace_1, "\t\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<EPackage> packages = ModelManager.loadMetaModel(metamodel);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<String> models = ModelManager.getModels(");
    _builder.append(this.className, "\t\t");
    _builder.append("Draw.class);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<String> mutants = ModelManager.getMutants(");
    _builder.append(this.className, "\t\t");
    _builder.append("Draw.class);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int totalTasks = models.size() + mutants.size();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("monitor.beginTask(\"Rendering models\", totalTasks);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// GENERATES Py code programs FROM SOURCE MODELS");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("File folder = new File(\"");
    _builder.append(folder, "\t\t");
    _builder.append("data/model\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("for (File file : folder.listFiles()) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (file.isFile()) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("String pathfile = file.getPath();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (pathfile.endsWith(\".model\") == true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String printPathfile = pathfile.replace(\"\\\\\", \"/\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("printPathfile = printPathfile.substring(printPathfile.lastIndexOf(\"/");
    String _name = project.getName();
    _builder.append(_name, "\t\t\t\t\t");
    _builder.append("/\") + (\"/");
    String _name_1 = project.getName();
    _builder.append(_name_1, "\t\t\t\t\t");
    _builder.append("/\").length(), printPathfile.length());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("monitor.subTask(\"Generating python code for mutant\" + printPathfile);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Resource model = ModelManager.loadModel(packages, pathfile);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String path = file.getName().replace(\".model\", \"\") + \"/\";");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String pycodefile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("path + ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"");
    String _name_2 = this.roots.get(0).getName();
    _builder.append(_name_2, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("String htmlfile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("path + ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"");
    String _name_3 = this.roots.get(0).getName();
    _builder.append(_name_3, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("String batfile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("path + ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"");
    String _name_4 = this.roots.get(0).getName();
    _builder.append(_name_4, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".bat\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("File pyfolder = new File(\"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("path);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("if (pyfolder.exists() != true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pyfolder.mkdirs();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter pywriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter = new PrintWriter(pycodefile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("String program = Py2Code.toPython(ModelManager.getRoot(model));");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter.println(program);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter batwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter = new PrintWriter(batfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"cd \\\\\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"cd ");
    _builder.append(folder, "\t\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + file.getName().replace(\".model\", \"\") + \"/\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"pygmentize -O full,style=emacs,linenos=1 -o ");
    String _name_5 = this.roots.get(0).getName();
    _builder.append(_name_5, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\") + \" ");
    String _name_6 = this.roots.get(0).getName();
    _builder.append(_name_6, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\"));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"exit\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String[] command = {\"cmd\", \"/c\", batfile};");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Process proc = Runtime.getRuntime().exec(command);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("proc.waitFor(); ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("BufferedReader br = new BufferedReader(new FileReader(htmlfile));");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Document doc = null; ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("StringBuilder sb = new StringBuilder();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("String line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("while (line != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("sb.append(line);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("sb.append(System.lineSeparator());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("String html = sb.toString();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("doc = Jsoup.parse(html);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} finally {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("br.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter htmlwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter = new PrintWriter(htmlfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter.println(doc.toString());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("//model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("//model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("monitor.worked(1);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("// GENERATES Python Code FROM MUTANTS");
    _builder.newLine();
    _builder.append("folder = new File(\"");
    _builder.append(folder);
    _builder.append("data/out\");");
    _builder.newLineIfNotEmpty();
    _builder.append("for (File exercise : folder.listFiles()) {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (exercise.isDirectory()) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (File file : exercise.listFiles()) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (file.isFile()) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("String pathfile = file.getPath();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (pathfile.endsWith(\".model\") == true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String printPathfile = pathfile.replace(\"\\\\\", \"/\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("printPathfile = printPathfile.substring(printPathfile.lastIndexOf(\"/");
    String _name_7 = project.getName();
    _builder.append(_name_7, "\t\t\t\t\t");
    _builder.append("/\") + (\"/");
    String _name_8 = project.getName();
    _builder.append(_name_8, "\t\t\t\t\t");
    _builder.append("/\").length(), printPathfile.length());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("monitor.subTask(\"Generating python code for mutant \" + printPathfile);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Resource model = ModelManager.loadModel(packages, pathfile);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String path = exercise.getName() + \"/\";");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String pycodefile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + path +");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"");
    String _name_9 = this.roots.get(0).getName();
    _builder.append(_name_9, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("String htmlfile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + path +");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"");
    String _name_10 = this.roots.get(0).getName();
    _builder.append(_name_10, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("String batfile = \"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + path + \"");
    String _name_11 = this.roots.get(0).getName();
    _builder.append(_name_11, "\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".bat\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("File pyfolder = new File(\"");
    _builder.append(folder, "\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + path);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("if (pyfolder.exists() != true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pyfolder.mkdirs();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter pywriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter = new PrintWriter(pycodefile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("String program = Py2Code.toPython(ModelManager.getRoot(model));");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter.println(program);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("pywriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter batwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter = new PrintWriter(batfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"cd \\\\\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"cd ");
    _builder.append(folder, "\t\t\t\t\t\t");
    _builder.append("src-gen/html/code/\" + exercise.getName() + \"/\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"pygmentize -O full,style=emacs,linenos=1 -o ");
    String _name_12 = this.roots.get(0).getName();
    _builder.append(_name_12, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\") + \" ");
    String _name_13 = this.roots.get(0).getName();
    _builder.append(_name_13, "\t\t\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\"));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.println(\"exit\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("batwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("String[] command = {\"cmd\", \"/c\", batfile};");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("Process proc = Runtime.getRuntime().exec(command);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("proc.waitFor(); ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("BufferedReader br = new BufferedReader(new FileReader(htmlfile));");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Document doc = null; ");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("StringBuilder sb = new StringBuilder();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("String line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("while (line != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("sb.append(line);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("sb.append(System.lineSeparator());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t        ");
    _builder.append("line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("String html = sb.toString();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("doc = Jsoup.parse(html);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} finally {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("br.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    \t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("PrintWriter htmlwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter = new PrintWriter(htmlfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter.println(doc.toString());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//htmlwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("//model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("//model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("//continue;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("monitor.worked(1);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("else {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("if (file.getName().equals(\"registry\") != true && !file.getName().endsWith(\"vs\")) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("File[] filesBlock = file.listFiles();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("for (File fileBlock : filesBlock) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("generatePyCode(fileBlock, packages, exercise, monitor);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("else {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (file.getName().equals(\"registry\") != true && !file.getName().endsWith(\"vs\")) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("File[] filesBlock = file.listFiles();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("for (File fileBlock : filesBlock) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("generatePyCode(fileBlock, packages, exercise, monitor);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("public void generatePyCode(File file, List<EPackage> packages, File exercise, IProgressMonitor monitor) throws MetaModelNotFoundException, ModelNotFoundException, FileNotFoundException {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (file.isFile()) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String pathfile = file.getPath();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (pathfile.endsWith(\".model\") == true) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String printPathfile = pathfile.replace(\"\\\\\", \"/\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("printPathfile = printPathfile.substring(printPathfile.lastIndexOf(\"/");
    String _name_14 = project.getName();
    _builder.append(_name_14, "\t\t\t");
    _builder.append("/\") + (\"/");
    String _name_15 = project.getName();
    _builder.append(_name_15, "\t\t\t");
    _builder.append("/\").length(), printPathfile.length());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("monitor.subTask(\"Generating python code for mutant \" + printPathfile);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Resource model = ModelManager.loadModel(packages, pathfile);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String path = file.getParent().replace(\"\\\\\", \"/\").substring(\"");
    _builder.append(folder, "\t\t\t");
    _builder.append("data/out\".length()) + \"/\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("String pycodefile = \"");
    _builder.append(folder, "\t\t\t");
    _builder.append("src-gen/html/code/\" + path + \"");
    String _name_16 = this.roots.get(0).getName();
    _builder.append(_name_16, "\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("String htmlfile = \"");
    _builder.append(folder, "\t\t\t");
    _builder.append("src-gen/html/code/\" + path + \"");
    String _name_17 = this.roots.get(0).getName();
    _builder.append(_name_17, "\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("String batfile = \"");
    _builder.append(folder, "\t\t\t");
    _builder.append("src-gen/html/code/\" + path + \"");
    String _name_18 = this.roots.get(0).getName();
    _builder.append(_name_18, "\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".bat\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("File exercisefolder = new File(\"");
    _builder.append(folder, "\t\t\t");
    _builder.append("src-gen/html/code/\" + path);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("if (exercisefolder.exists() != true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("exercisefolder.mkdirs();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PrintWriter pywriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("pywriter = new PrintWriter(pycodefile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("String program = Py2Code.toPython(ModelManager.getRoot(model));");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("pywriter.println(program);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("pywriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (FileNotFoundException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PrintWriter batwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter = new PrintWriter(batfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter.println(\"cd \\\\\");");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter.println(\"cd ");
    _builder.append(folder, "\t\t\t\t");
    _builder.append("src-gen/html/code/\" + path);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter.println(\"pygmentize -O full,style=emacs,linenos=1 -o ");
    String _name_19 = this.roots.get(0).getName();
    _builder.append(_name_19, "\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".html\") + \" ");
    String _name_20 = this.roots.get(0).getName();
    _builder.append(_name_20, "\t\t\t\t");
    _builder.append("_\" + file.getName().replace(\".model\", \".py\"));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter.println(\"exit\");");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("batwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} catch (Exception ex) {}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String[] command = {\"cmd\", \"/c\", batfile};");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("Process proc = Runtime.getRuntime().exec(command);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("proc.waitFor(); ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("BufferedReader br = new BufferedReader(new FileReader(htmlfile));");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Document doc = null; ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("StringBuilder sb = new StringBuilder();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("String line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("while (line != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("sb.append(line);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("sb.append(System.lineSeparator());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("line = br.readLine();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("String html = sb.toString();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("doc = Jsoup.parse(html);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} finally {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("br.close();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} catch (IOException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PrintWriter htmlwriter = null;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//htmlwriter = new PrintWriter(htmlfile, \"UTF-8\");");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//htmlwriter.println(doc.toString());");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//htmlwriter.close();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("//} catch (UnsupportedEncodingException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//Reload input");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("//model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//} catch (Exception ex) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("//}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("model.load(null);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("monitor.worked(1);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("else {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("generatePyCodeRecursive(file, packages, exercise, monitor);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("private void generatePyCodeRecursive(File file, List<EPackage> packages, File exercise, IProgressMonitor monitor) throws FileNotFoundException, MetaModelNotFoundException, ModelNotFoundException {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (file.getName().equals(\"registry\") != true && !file.getName().endsWith(\"vs\")) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("File[] filesInBlock = file.listFiles();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (filesInBlock != null && filesInBlock.length > 0) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("for (File fileInBlock : filesInBlock) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (fileInBlock.isFile()) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("generatePyCode(fileInBlock, packages, exercise, monitor);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("else {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("generatePyCodeRecursive(fileInBlock, packages, exercise, monitor);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("public Object execute(ExecutionEvent event) throws ExecutionException {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("RunMutatorPyCodeWithProgress runMutatorPyCodeWithProgress = new RunMutatorPyCodeWithProgress();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ProgressMonitorDialog monitor = new ProgressMonitorDialog(new Shell(new Display()));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("monitor.run(true, true, runMutatorPyCodeWithProgress);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("} catch (InvocationTargetException e) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("} catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("public void run() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("execute(null);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("catch (ExecutionException e) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
