/*
 * generated by Xtext 2.30.0
 */
package wodeledu.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodeledu.dsls.ModelTextRuntimeModule;
import wodeledu.dsls.ModelTextStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ModelTextIdeSetup extends ModelTextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModelTextRuntimeModule(), new ModelTextIdeModule()));
	}
	
}
