source.. = src-gen/,\
           src/,\
           /
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               bin/,\
               MutationTestingApp.sys,\
               network_traces/,\
               data/
