source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               bin/,\
               schema/,\
               lib/,\
               emtl/,\
               icons/,\
               wodeltest/,\
               resources/
src.includes = src/
