/*
 * generated by Xtext 2.36.0
 */
package wodel.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodel.dsls.WodelRuntimeModule;
import wodel.dsls.WodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WodelIdeSetup extends WodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WodelRuntimeModule(), new WodelIdeModule()));
	}
	
}
