/*
 * generated by Xtext 2.40.0
 */
package wodel.dsls.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import wodel.dsls.parser.antlr.internal.InternalASPLEParser;
import wodel.dsls.services.ASPLEGrammarAccess;

public class ASPLEParser extends AbstractAntlrParser {

	@Inject
	private ASPLEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalASPLEParser createParser(XtextTokenStream stream) {
		return new InternalASPLEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ASPLEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ASPLEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
