/*
 * generated by Xtext 2.30.0
 */
package wodeledu.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModelTextUiModule extends AbstractModelTextUiModule {

	public ModelTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
