/*
 * generated by Xtext 2.42.0
 */
package wodeledu.dsls.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import wodeledu.dsls.parser.antlr.internal.InternalEduTestParser;
import wodeledu.dsls.services.EduTestGrammarAccess;

public class EduTestParser extends AbstractAntlrParser {

	@Inject
	private EduTestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEduTestParser createParser(XtextTokenStream stream) {
		return new InternalEduTestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public EduTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EduTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
