/*
 * generated by Xtext 2.41.0
 */
package wodeledu.dsls.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MutaTextGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Configuration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfigurationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMetamodelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetamodelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetamodelEStringParserRuleCall_2_0 = (RuleCall)cMetamodelAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cOptionsAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cOptionsOptionParserRuleCall_3_0_0 = (RuleCall)cOptionsAssignment_3_0.eContents().get(0);
		private final Assignment cOptionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOptionsOptionParserRuleCall_3_1_0 = (RuleCall)cOptionsAssignment_3_1.eContents().get(0);
		
		//Configuration returns Configuration:
		//    {Configuration}
		//    'metamodel' metamodel=EString
		//    (options+=Option (options+=Option)*)?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Configuration}
		//'metamodel' metamodel=EString
		//(options+=Option (options+=Option)*)?
		public Group getGroup() { return cGroup; }
		
		//{Configuration}
		public Action getConfigurationAction_0() { return cConfigurationAction_0; }
		
		//'metamodel'
		public Keyword getMetamodelKeyword_1() { return cMetamodelKeyword_1; }
		
		//metamodel=EString
		public Assignment getMetamodelAssignment_2() { return cMetamodelAssignment_2; }
		
		//EString
		public RuleCall getMetamodelEStringParserRuleCall_2_0() { return cMetamodelEStringParserRuleCall_2_0; }
		
		//(options+=Option (options+=Option)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//options+=Option
		public Assignment getOptionsAssignment_3_0() { return cOptionsAssignment_3_0; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_3_0_0() { return cOptionsOptionParserRuleCall_3_0_0; }
		
		//(options+=Option)*
		public Assignment getOptionsAssignment_3_1() { return cOptionsAssignment_3_1; }
		
		//Option
		public RuleCall getOptionsOptionParserRuleCall_3_1_0() { return cOptionsOptionParserRuleCall_3_1_0; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Option");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOptionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeEClassCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeEClassEStringParserRuleCall_2_0_1 = (RuleCall)cTypeEClassCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cObjectAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cObjectEObjectCrossReference_3_1_0 = (CrossReference)cObjectAssignment_3_1.eContents().get(0);
		private final RuleCall cObjectEObjectEStringParserRuleCall_3_1_0_1 = (RuleCall)cObjectEObjectCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValidAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValidTextParserRuleCall_5_0 = (RuleCall)cValidAssignment_5.eContents().get(0);
		private final Keyword cSolidusKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInvalidAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cInvalidTextParserRuleCall_7_0 = (RuleCall)cInvalidAssignment_7.eContents().get(0);
		
		//Option returns Option:
		//    {Option}
		//    '>' type=[ecore::EClass|EString] ('('object=[ecore::EObject|EString]')')? ':' valid=Text '/' invalid=Text
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Option}
		//'>' type=[ecore::EClass|EString] ('('object=[ecore::EObject|EString]')')? ':' valid=Text '/' invalid=Text
		public Group getGroup() { return cGroup; }
		
		//{Option}
		public Action getOptionAction_0() { return cOptionAction_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1() { return cGreaterThanSignKeyword_1; }
		
		//type=[ecore::EClass|EString]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[ecore::EClass|EString]
		public CrossReference getTypeEClassCrossReference_2_0() { return cTypeEClassCrossReference_2_0; }
		
		//EString
		public RuleCall getTypeEClassEStringParserRuleCall_2_0_1() { return cTypeEClassEStringParserRuleCall_2_0_1; }
		
		//('('object=[ecore::EObject|EString]')')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//object=[ecore::EObject|EString]
		public Assignment getObjectAssignment_3_1() { return cObjectAssignment_3_1; }
		
		//[ecore::EObject|EString]
		public CrossReference getObjectEObjectCrossReference_3_1_0() { return cObjectEObjectCrossReference_3_1_0; }
		
		//EString
		public RuleCall getObjectEObjectEStringParserRuleCall_3_1_0_1() { return cObjectEObjectEStringParserRuleCall_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//valid=Text
		public Assignment getValidAssignment_5() { return cValidAssignment_5; }
		
		//Text
		public RuleCall getValidTextParserRuleCall_5_0() { return cValidTextParserRuleCall_5_0; }
		
		//'/'
		public Keyword getSolidusKeyword_6() { return cSolidusKeyword_6; }
		
		//invalid=Text
		public Assignment getInvalidAssignment_7() { return cInvalidAssignment_7; }
		
		//Text
		public RuleCall getInvalidTextParserRuleCall_7_0() { return cInvalidTextParserRuleCall_7_0; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cWordsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cWordsWordParserRuleCall_1_0_0 = (RuleCall)cWordsAssignment_1_0.eContents().get(0);
		private final Assignment cWordsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cWordsWordParserRuleCall_1_1_0 = (RuleCall)cWordsAssignment_1_1.eContents().get(0);
		
		//Text returns Text:
		//    {Text}
		//    ((words+=Word) (words+=Word)*)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Text}
		//((words+=Word) (words+=Word)*)?
		public Group getGroup() { return cGroup; }
		
		//{Text}
		public Action getTextAction_0() { return cTextAction_0; }
		
		//((words+=Word) (words+=Word)*)?
		public Group getGroup_1() { return cGroup_1; }
		
		//(words+=Word)
		public Assignment getWordsAssignment_1_0() { return cWordsAssignment_1_0; }
		
		//Word
		public RuleCall getWordsWordParserRuleCall_1_0_0() { return cWordsWordParserRuleCall_1_0_0; }
		
		//(words+=Word)*
		public Assignment getWordsAssignment_1_1() { return cWordsAssignment_1_1; }
		
		//Word
		public RuleCall getWordsWordParserRuleCall_1_1_0() { return cWordsWordParserRuleCall_1_1_0; }
	}
	public class WordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Word");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cConstantParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVariableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Word returns Word:
		//    Constant | Variable
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Constant | Variable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Constant
		public RuleCall getConstantParserRuleCall_0() { return cConstantParserRuleCall_0; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_1() { return cVariableParserRuleCall_1; }
	}
	public class ConstantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Constant");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConstantAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Constant returns Constant:
		//    {Constant}
		//    value=EString
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Constant}
		//value=EString
		public Group getGroup() { return cGroup; }
		
		//{Constant}
		public Action getConstantAction_0() { return cConstantAction_0; }
		
		//value=EString
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_1_0() { return cValueEStringParserRuleCall_1_0; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeVariableTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		
		//Variable returns Variable:
		//    {Variable}
		//    type=VariableType
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable}
		//type=VariableType
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//type=VariableType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//VariableType
		public RuleCall getTypeVariableTypeEnumRuleCall_1_0() { return cTypeVariableTypeEnumRuleCall_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class VariableTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "wodeledu.dsls.MutaText.VariableType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cObjectEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cObjectObjectKeyword_0_0 = (Keyword)cObjectEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAttNameEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAttNameAttNameKeyword_1_0 = (Keyword)cAttNameEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cOldValueEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cOldValueOldValueKeyword_2_0 = (Keyword)cOldValueEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cNewValueEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cNewValueNewValueKeyword_3_0 = (Keyword)cNewValueEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRefNameEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRefNameRefNameKeyword_4_0 = (Keyword)cRefNameEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cFromObjectEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cFromObjectFromObjectKeyword_5_0 = (Keyword)cFromObjectEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cOldFromObjectEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cOldFromObjectOldFromObjectKeyword_6_0 = (Keyword)cOldFromObjectEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cSrcRefNameEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cSrcRefNameSrcRefNameKeyword_7_0 = (Keyword)cSrcRefNameEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cToObjectEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cToObjectToObjectKeyword_8_0 = (Keyword)cToObjectEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cOldToObjectEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cOldToObjectOldToObjectKeyword_9_0 = (Keyword)cOldToObjectEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cFirstRefNameEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cFirstRefNameFirstRefNameKeyword_10_0 = (Keyword)cFirstRefNameEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cFirstObjectEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cFirstObjectFirstObjectKeyword_11_0 = (Keyword)cFirstObjectEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cFirstFromObjectEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cFirstFromObjectFirstFromObjectKeyword_12_0 = (Keyword)cFirstFromObjectEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cFirstToObjectEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cFirstToObjectFirstToObjectKeyword_13_0 = (Keyword)cFirstToObjectEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cSecondRefNameEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cSecondRefNameSecondRefNameKeyword_14_0 = (Keyword)cSecondRefNameEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cSecondObjectEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cSecondObjectSecondObjectKeyword_15_0 = (Keyword)cSecondObjectEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cSecondFromObjectEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cSecondFromObjectSecondFromObjectKeyword_16_0 = (Keyword)cSecondFromObjectEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cSecondToObjectEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cSecondToObjectSecondToObjectKeyword_17_0 = (Keyword)cSecondToObjectEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cFirstAttNameEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cFirstAttNameFirstAttNameKeyword_18_0 = (Keyword)cFirstAttNameEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cFirstValueEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cFirstValueFirstValueKeyword_19_0 = (Keyword)cFirstValueEnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cSecondAttNameEnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cSecondAttNameSecondAttNameKeyword_20_0 = (Keyword)cSecondAttNameEnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cSecondValueEnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cSecondValueSecondValueKeyword_21_0 = (Keyword)cSecondValueEnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cValueEnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cValueValueKeyword_22_0 = (Keyword)cValueEnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedObjectEnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cDescribedObjectDescribedObjectKeyword_23_0 = (Keyword)cDescribedObjectEnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedFromObjectEnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cDescribedFromObjectDescribedFromObjectKeyword_24_0 = (Keyword)cDescribedFromObjectEnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedOldFromObjectEnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cDescribedOldFromObjectDescribedOldFromObjectKeyword_25_0 = (Keyword)cDescribedOldFromObjectEnumLiteralDeclaration_25.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedToObjectEnumLiteralDeclaration_26 = (EnumLiteralDeclaration)cAlternatives.eContents().get(26);
		private final Keyword cDescribedToObjectDescribedToObjectKeyword_26_0 = (Keyword)cDescribedToObjectEnumLiteralDeclaration_26.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedOldToObjectEnumLiteralDeclaration_27 = (EnumLiteralDeclaration)cAlternatives.eContents().get(27);
		private final Keyword cDescribedOldToObjectDescribedOldToObjectKeyword_27_0 = (Keyword)cDescribedOldToObjectEnumLiteralDeclaration_27.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedFirstObjectEnumLiteralDeclaration_28 = (EnumLiteralDeclaration)cAlternatives.eContents().get(28);
		private final Keyword cDescribedFirstObjectDescribedFirstObjectKeyword_28_0 = (Keyword)cDescribedFirstObjectEnumLiteralDeclaration_28.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedFirstFromObjectEnumLiteralDeclaration_29 = (EnumLiteralDeclaration)cAlternatives.eContents().get(29);
		private final Keyword cDescribedFirstFromObjectDescribedFirstFromObjectKeyword_29_0 = (Keyword)cDescribedFirstFromObjectEnumLiteralDeclaration_29.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedFirstToObjectEnumLiteralDeclaration_30 = (EnumLiteralDeclaration)cAlternatives.eContents().get(30);
		private final Keyword cDescribedFirstToObjectDescribedFirstToObjectKeyword_30_0 = (Keyword)cDescribedFirstToObjectEnumLiteralDeclaration_30.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedSecondObjectEnumLiteralDeclaration_31 = (EnumLiteralDeclaration)cAlternatives.eContents().get(31);
		private final Keyword cDescribedSecondObjectDescribedSecondObjectKeyword_31_0 = (Keyword)cDescribedSecondObjectEnumLiteralDeclaration_31.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedSecondFromObjectEnumLiteralDeclaration_32 = (EnumLiteralDeclaration)cAlternatives.eContents().get(32);
		private final Keyword cDescribedSecondFromObjectDescribedSecondFromObjectKeyword_32_0 = (Keyword)cDescribedSecondFromObjectEnumLiteralDeclaration_32.eContents().get(0);
		private final EnumLiteralDeclaration cDescribedSecondToObjectEnumLiteralDeclaration_33 = (EnumLiteralDeclaration)cAlternatives.eContents().get(33);
		private final Keyword cDescribedSecondToObjectDescribedSecondToObjectKeyword_33_0 = (Keyword)cDescribedSecondToObjectEnumLiteralDeclaration_33.eContents().get(0);
		
		//enum VariableType returns VariableType:
		//    object = '%object' |
		////AttributeChanged
		//    attName = '%attName' |
		//    oldValue = '%oldValue' |
		//    newValue = '%newValue' |
		////SourceReferenceChanged
		//    refName = '%refName' |
		//    fromObject = '%fromObject' |
		//    oldFromObject = '%oldFromObject' |
		////TargetReferenceChanged
		//    srcRefName = '%srcRefName' |
		//    toObject = '%toObject' |
		//    oldToObject = '%oldToObject' |
		////ReferenceSwap
		//    firstRefName = '%firstRefName' |
		//    firstObject = '%firstObject' |
		//    firstFromObject = '%firstFromObject' |
		//    firstToObject = '%firstToObject' |
		//    secondRefName = '%secondRefName' |
		//    secondObject = '%secondObject' |
		//    secondFromObject = '%secondFromObject' |
		//    secondToObject = '%secondToObject' |
		////AttributeSwap
		//    firstAttName = '%firstAttName' |
		//    firstValue = '%firstValue' |
		//    secondAttName = '%secondAttName' |
		//    secondValue = '%secondValue' |
		////Remaining
		//    value = '%value' |
		//    describedObject = '%describedObject' |
		//    describedFromObject = '%describedFromObject' |
		//    describedOldFromObject = '%describedOldFromObject' |
		//    describedToObject = '%describedToObject' |
		//    describedOldToObject = '%describedOldToObject' |
		//    describedFirstObject = '%describedFirstObject' |
		//    describedFirstFromObject = '%describedFirstFromObject' |
		//    describedFirstToObject = '%describedFirstToObject' |
		//    describedSecondObject = '%describedSecondObject' |
		//    describedSecondFromObject = '%describedSecondFromObject' |
		//    describedSecondToObject = '%describedSecondToObject'
		//    ;
		public EnumRule getRule() { return rule; }
		
		//    object = '%object' |
		////AttributeChanged
		//    attName = '%attName' |
		//    oldValue = '%oldValue' |
		//    newValue = '%newValue' |
		////SourceReferenceChanged
		//    refName = '%refName' |
		//    fromObject = '%fromObject' |
		//    oldFromObject = '%oldFromObject' |
		////TargetReferenceChanged
		//    srcRefName = '%srcRefName' |
		//    toObject = '%toObject' |
		//    oldToObject = '%oldToObject' |
		////ReferenceSwap
		//    firstRefName = '%firstRefName' |
		//    firstObject = '%firstObject' |
		//    firstFromObject = '%firstFromObject' |
		//    firstToObject = '%firstToObject' |
		//    secondRefName = '%secondRefName' |
		//    secondObject = '%secondObject' |
		//    secondFromObject = '%secondFromObject' |
		//    secondToObject = '%secondToObject' |
		////AttributeSwap
		//    firstAttName = '%firstAttName' |
		//    firstValue = '%firstValue' |
		//    secondAttName = '%secondAttName' |
		//    secondValue = '%secondValue' |
		////Remaining
		//    value = '%value' |
		//    describedObject = '%describedObject' |
		//    describedFromObject = '%describedFromObject' |
		//    describedOldFromObject = '%describedOldFromObject' |
		//    describedToObject = '%describedToObject' |
		//    describedOldToObject = '%describedOldToObject' |
		//    describedFirstObject = '%describedFirstObject' |
		//    describedFirstFromObject = '%describedFirstFromObject' |
		//    describedFirstToObject = '%describedFirstToObject' |
		//    describedSecondObject = '%describedSecondObject' |
		//    describedSecondFromObject = '%describedSecondFromObject' |
		//    describedSecondToObject = '%describedSecondToObject'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//object = '%object'
		public EnumLiteralDeclaration getObjectEnumLiteralDeclaration_0() { return cObjectEnumLiteralDeclaration_0; }
		
		//'%object'
		public Keyword getObjectObjectKeyword_0_0() { return cObjectObjectKeyword_0_0; }
		
		////AttributeChanged
		//    attName = '%attName'
		public EnumLiteralDeclaration getAttNameEnumLiteralDeclaration_1() { return cAttNameEnumLiteralDeclaration_1; }
		
		//'%attName'
		public Keyword getAttNameAttNameKeyword_1_0() { return cAttNameAttNameKeyword_1_0; }
		
		//oldValue = '%oldValue'
		public EnumLiteralDeclaration getOldValueEnumLiteralDeclaration_2() { return cOldValueEnumLiteralDeclaration_2; }
		
		//'%oldValue'
		public Keyword getOldValueOldValueKeyword_2_0() { return cOldValueOldValueKeyword_2_0; }
		
		//newValue = '%newValue'
		public EnumLiteralDeclaration getNewValueEnumLiteralDeclaration_3() { return cNewValueEnumLiteralDeclaration_3; }
		
		//'%newValue'
		public Keyword getNewValueNewValueKeyword_3_0() { return cNewValueNewValueKeyword_3_0; }
		
		////SourceReferenceChanged
		//    refName = '%refName'
		public EnumLiteralDeclaration getRefNameEnumLiteralDeclaration_4() { return cRefNameEnumLiteralDeclaration_4; }
		
		//'%refName'
		public Keyword getRefNameRefNameKeyword_4_0() { return cRefNameRefNameKeyword_4_0; }
		
		//fromObject = '%fromObject'
		public EnumLiteralDeclaration getFromObjectEnumLiteralDeclaration_5() { return cFromObjectEnumLiteralDeclaration_5; }
		
		//'%fromObject'
		public Keyword getFromObjectFromObjectKeyword_5_0() { return cFromObjectFromObjectKeyword_5_0; }
		
		//oldFromObject = '%oldFromObject'
		public EnumLiteralDeclaration getOldFromObjectEnumLiteralDeclaration_6() { return cOldFromObjectEnumLiteralDeclaration_6; }
		
		//'%oldFromObject'
		public Keyword getOldFromObjectOldFromObjectKeyword_6_0() { return cOldFromObjectOldFromObjectKeyword_6_0; }
		
		////TargetReferenceChanged
		//    srcRefName = '%srcRefName'
		public EnumLiteralDeclaration getSrcRefNameEnumLiteralDeclaration_7() { return cSrcRefNameEnumLiteralDeclaration_7; }
		
		//'%srcRefName'
		public Keyword getSrcRefNameSrcRefNameKeyword_7_0() { return cSrcRefNameSrcRefNameKeyword_7_0; }
		
		//toObject = '%toObject'
		public EnumLiteralDeclaration getToObjectEnumLiteralDeclaration_8() { return cToObjectEnumLiteralDeclaration_8; }
		
		//'%toObject'
		public Keyword getToObjectToObjectKeyword_8_0() { return cToObjectToObjectKeyword_8_0; }
		
		//oldToObject = '%oldToObject'
		public EnumLiteralDeclaration getOldToObjectEnumLiteralDeclaration_9() { return cOldToObjectEnumLiteralDeclaration_9; }
		
		//'%oldToObject'
		public Keyword getOldToObjectOldToObjectKeyword_9_0() { return cOldToObjectOldToObjectKeyword_9_0; }
		
		////ReferenceSwap
		//    firstRefName = '%firstRefName'
		public EnumLiteralDeclaration getFirstRefNameEnumLiteralDeclaration_10() { return cFirstRefNameEnumLiteralDeclaration_10; }
		
		//'%firstRefName'
		public Keyword getFirstRefNameFirstRefNameKeyword_10_0() { return cFirstRefNameFirstRefNameKeyword_10_0; }
		
		//firstObject = '%firstObject'
		public EnumLiteralDeclaration getFirstObjectEnumLiteralDeclaration_11() { return cFirstObjectEnumLiteralDeclaration_11; }
		
		//'%firstObject'
		public Keyword getFirstObjectFirstObjectKeyword_11_0() { return cFirstObjectFirstObjectKeyword_11_0; }
		
		//firstFromObject = '%firstFromObject'
		public EnumLiteralDeclaration getFirstFromObjectEnumLiteralDeclaration_12() { return cFirstFromObjectEnumLiteralDeclaration_12; }
		
		//'%firstFromObject'
		public Keyword getFirstFromObjectFirstFromObjectKeyword_12_0() { return cFirstFromObjectFirstFromObjectKeyword_12_0; }
		
		//firstToObject = '%firstToObject'
		public EnumLiteralDeclaration getFirstToObjectEnumLiteralDeclaration_13() { return cFirstToObjectEnumLiteralDeclaration_13; }
		
		//'%firstToObject'
		public Keyword getFirstToObjectFirstToObjectKeyword_13_0() { return cFirstToObjectFirstToObjectKeyword_13_0; }
		
		//secondRefName = '%secondRefName'
		public EnumLiteralDeclaration getSecondRefNameEnumLiteralDeclaration_14() { return cSecondRefNameEnumLiteralDeclaration_14; }
		
		//'%secondRefName'
		public Keyword getSecondRefNameSecondRefNameKeyword_14_0() { return cSecondRefNameSecondRefNameKeyword_14_0; }
		
		//secondObject = '%secondObject'
		public EnumLiteralDeclaration getSecondObjectEnumLiteralDeclaration_15() { return cSecondObjectEnumLiteralDeclaration_15; }
		
		//'%secondObject'
		public Keyword getSecondObjectSecondObjectKeyword_15_0() { return cSecondObjectSecondObjectKeyword_15_0; }
		
		//secondFromObject = '%secondFromObject'
		public EnumLiteralDeclaration getSecondFromObjectEnumLiteralDeclaration_16() { return cSecondFromObjectEnumLiteralDeclaration_16; }
		
		//'%secondFromObject'
		public Keyword getSecondFromObjectSecondFromObjectKeyword_16_0() { return cSecondFromObjectSecondFromObjectKeyword_16_0; }
		
		//secondToObject = '%secondToObject'
		public EnumLiteralDeclaration getSecondToObjectEnumLiteralDeclaration_17() { return cSecondToObjectEnumLiteralDeclaration_17; }
		
		//'%secondToObject'
		public Keyword getSecondToObjectSecondToObjectKeyword_17_0() { return cSecondToObjectSecondToObjectKeyword_17_0; }
		
		////AttributeSwap
		//    firstAttName = '%firstAttName'
		public EnumLiteralDeclaration getFirstAttNameEnumLiteralDeclaration_18() { return cFirstAttNameEnumLiteralDeclaration_18; }
		
		//'%firstAttName'
		public Keyword getFirstAttNameFirstAttNameKeyword_18_0() { return cFirstAttNameFirstAttNameKeyword_18_0; }
		
		//firstValue = '%firstValue'
		public EnumLiteralDeclaration getFirstValueEnumLiteralDeclaration_19() { return cFirstValueEnumLiteralDeclaration_19; }
		
		//'%firstValue'
		public Keyword getFirstValueFirstValueKeyword_19_0() { return cFirstValueFirstValueKeyword_19_0; }
		
		//secondAttName = '%secondAttName'
		public EnumLiteralDeclaration getSecondAttNameEnumLiteralDeclaration_20() { return cSecondAttNameEnumLiteralDeclaration_20; }
		
		//'%secondAttName'
		public Keyword getSecondAttNameSecondAttNameKeyword_20_0() { return cSecondAttNameSecondAttNameKeyword_20_0; }
		
		//secondValue = '%secondValue'
		public EnumLiteralDeclaration getSecondValueEnumLiteralDeclaration_21() { return cSecondValueEnumLiteralDeclaration_21; }
		
		//'%secondValue'
		public Keyword getSecondValueSecondValueKeyword_21_0() { return cSecondValueSecondValueKeyword_21_0; }
		
		////Remaining
		//    value = '%value'
		public EnumLiteralDeclaration getValueEnumLiteralDeclaration_22() { return cValueEnumLiteralDeclaration_22; }
		
		//'%value'
		public Keyword getValueValueKeyword_22_0() { return cValueValueKeyword_22_0; }
		
		//describedObject = '%describedObject'
		public EnumLiteralDeclaration getDescribedObjectEnumLiteralDeclaration_23() { return cDescribedObjectEnumLiteralDeclaration_23; }
		
		//'%describedObject'
		public Keyword getDescribedObjectDescribedObjectKeyword_23_0() { return cDescribedObjectDescribedObjectKeyword_23_0; }
		
		//describedFromObject = '%describedFromObject'
		public EnumLiteralDeclaration getDescribedFromObjectEnumLiteralDeclaration_24() { return cDescribedFromObjectEnumLiteralDeclaration_24; }
		
		//'%describedFromObject'
		public Keyword getDescribedFromObjectDescribedFromObjectKeyword_24_0() { return cDescribedFromObjectDescribedFromObjectKeyword_24_0; }
		
		//describedOldFromObject = '%describedOldFromObject'
		public EnumLiteralDeclaration getDescribedOldFromObjectEnumLiteralDeclaration_25() { return cDescribedOldFromObjectEnumLiteralDeclaration_25; }
		
		//'%describedOldFromObject'
		public Keyword getDescribedOldFromObjectDescribedOldFromObjectKeyword_25_0() { return cDescribedOldFromObjectDescribedOldFromObjectKeyword_25_0; }
		
		//describedToObject = '%describedToObject'
		public EnumLiteralDeclaration getDescribedToObjectEnumLiteralDeclaration_26() { return cDescribedToObjectEnumLiteralDeclaration_26; }
		
		//'%describedToObject'
		public Keyword getDescribedToObjectDescribedToObjectKeyword_26_0() { return cDescribedToObjectDescribedToObjectKeyword_26_0; }
		
		//describedOldToObject = '%describedOldToObject'
		public EnumLiteralDeclaration getDescribedOldToObjectEnumLiteralDeclaration_27() { return cDescribedOldToObjectEnumLiteralDeclaration_27; }
		
		//'%describedOldToObject'
		public Keyword getDescribedOldToObjectDescribedOldToObjectKeyword_27_0() { return cDescribedOldToObjectDescribedOldToObjectKeyword_27_0; }
		
		//describedFirstObject = '%describedFirstObject'
		public EnumLiteralDeclaration getDescribedFirstObjectEnumLiteralDeclaration_28() { return cDescribedFirstObjectEnumLiteralDeclaration_28; }
		
		//'%describedFirstObject'
		public Keyword getDescribedFirstObjectDescribedFirstObjectKeyword_28_0() { return cDescribedFirstObjectDescribedFirstObjectKeyword_28_0; }
		
		//describedFirstFromObject = '%describedFirstFromObject'
		public EnumLiteralDeclaration getDescribedFirstFromObjectEnumLiteralDeclaration_29() { return cDescribedFirstFromObjectEnumLiteralDeclaration_29; }
		
		//'%describedFirstFromObject'
		public Keyword getDescribedFirstFromObjectDescribedFirstFromObjectKeyword_29_0() { return cDescribedFirstFromObjectDescribedFirstFromObjectKeyword_29_0; }
		
		//describedFirstToObject = '%describedFirstToObject'
		public EnumLiteralDeclaration getDescribedFirstToObjectEnumLiteralDeclaration_30() { return cDescribedFirstToObjectEnumLiteralDeclaration_30; }
		
		//'%describedFirstToObject'
		public Keyword getDescribedFirstToObjectDescribedFirstToObjectKeyword_30_0() { return cDescribedFirstToObjectDescribedFirstToObjectKeyword_30_0; }
		
		//describedSecondObject = '%describedSecondObject'
		public EnumLiteralDeclaration getDescribedSecondObjectEnumLiteralDeclaration_31() { return cDescribedSecondObjectEnumLiteralDeclaration_31; }
		
		//'%describedSecondObject'
		public Keyword getDescribedSecondObjectDescribedSecondObjectKeyword_31_0() { return cDescribedSecondObjectDescribedSecondObjectKeyword_31_0; }
		
		//describedSecondFromObject = '%describedSecondFromObject'
		public EnumLiteralDeclaration getDescribedSecondFromObjectEnumLiteralDeclaration_32() { return cDescribedSecondFromObjectEnumLiteralDeclaration_32; }
		
		//'%describedSecondFromObject'
		public Keyword getDescribedSecondFromObjectDescribedSecondFromObjectKeyword_32_0() { return cDescribedSecondFromObjectDescribedSecondFromObjectKeyword_32_0; }
		
		//describedSecondToObject = '%describedSecondToObject'
		public EnumLiteralDeclaration getDescribedSecondToObjectEnumLiteralDeclaration_33() { return cDescribedSecondToObjectEnumLiteralDeclaration_33; }
		
		//'%describedSecondToObject'
		public Keyword getDescribedSecondToObjectDescribedSecondToObjectKeyword_33_0() { return cDescribedSecondToObjectDescribedSecondToObjectKeyword_33_0; }
	}
	
	private final ConfigurationElements pConfiguration;
	private final OptionElements pOption;
	private final TextElements pText;
	private final WordElements pWord;
	private final ConstantElements pConstant;
	private final VariableElements pVariable;
	private final VariableTypeElements eVariableType;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MutaTextGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pConfiguration = new ConfigurationElements();
		this.pOption = new OptionElements();
		this.pText = new TextElements();
		this.pWord = new WordElements();
		this.pConstant = new ConstantElements();
		this.pVariable = new VariableElements();
		this.eVariableType = new VariableTypeElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("wodeledu.dsls.MutaText".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Configuration returns Configuration:
	//    {Configuration}
	//    'metamodel' metamodel=EString
	//    (options+=Option (options+=Option)*)?
	//    ;
	public ConfigurationElements getConfigurationAccess() {
		return pConfiguration;
	}
	
	public ParserRule getConfigurationRule() {
		return getConfigurationAccess().getRule();
	}
	
	//Option returns Option:
	//    {Option}
	//    '>' type=[ecore::EClass|EString] ('('object=[ecore::EObject|EString]')')? ':' valid=Text '/' invalid=Text
	//;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//Text returns Text:
	//    {Text}
	//    ((words+=Word) (words+=Word)*)?
	//;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Word returns Word:
	//    Constant | Variable
	//;
	public WordElements getWordAccess() {
		return pWord;
	}
	
	public ParserRule getWordRule() {
		return getWordAccess().getRule();
	}
	
	//Constant returns Constant:
	//    {Constant}
	//    value=EString
	//;
	public ConstantElements getConstantAccess() {
		return pConstant;
	}
	
	public ParserRule getConstantRule() {
		return getConstantAccess().getRule();
	}
	
	//Variable returns Variable:
	//    {Variable}
	//    type=VariableType
	//;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//enum VariableType returns VariableType:
	//    object = '%object' |
	////AttributeChanged
	//    attName = '%attName' |
	//    oldValue = '%oldValue' |
	//    newValue = '%newValue' |
	////SourceReferenceChanged
	//    refName = '%refName' |
	//    fromObject = '%fromObject' |
	//    oldFromObject = '%oldFromObject' |
	////TargetReferenceChanged
	//    srcRefName = '%srcRefName' |
	//    toObject = '%toObject' |
	//    oldToObject = '%oldToObject' |
	////ReferenceSwap
	//    firstRefName = '%firstRefName' |
	//    firstObject = '%firstObject' |
	//    firstFromObject = '%firstFromObject' |
	//    firstToObject = '%firstToObject' |
	//    secondRefName = '%secondRefName' |
	//    secondObject = '%secondObject' |
	//    secondFromObject = '%secondFromObject' |
	//    secondToObject = '%secondToObject' |
	////AttributeSwap
	//    firstAttName = '%firstAttName' |
	//    firstValue = '%firstValue' |
	//    secondAttName = '%secondAttName' |
	//    secondValue = '%secondValue' |
	////Remaining
	//    value = '%value' |
	//    describedObject = '%describedObject' |
	//    describedFromObject = '%describedFromObject' |
	//    describedOldFromObject = '%describedOldFromObject' |
	//    describedToObject = '%describedToObject' |
	//    describedOldToObject = '%describedOldToObject' |
	//    describedFirstObject = '%describedFirstObject' |
	//    describedFirstFromObject = '%describedFirstFromObject' |
	//    describedFirstToObject = '%describedFirstToObject' |
	//    describedSecondObject = '%describedSecondObject' |
	//    describedSecondFromObject = '%describedSecondFromObject' |
	//    describedSecondToObject = '%describedSecondToObject'
	//    ;
	public VariableTypeElements getVariableTypeAccess() {
		return eVariableType;
	}
	
	public EnumRule getVariableTypeRule() {
		return getVariableTypeAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
