source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               bin/,\
               icons/,\
               models/,\
               mutator/,\
               plugin.xml,\
               wodeltest/,\
               lib/,\
               resources/

