/*
 * generated by Xtext 2.30.0
 */
package wodel.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodel.dsls.ASPLERuntimeModule;
import wodel.dsls.ASPLEStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ASPLEIdeSetup extends ASPLEStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ASPLERuntimeModule(), new ASPLEIdeModule()));
	}
	
}
